Repository surfstudio/flutter-bottom-sheet, pull requests merged in 2023-08, with the labels that each got.

#82 Update README.md build status
  README.md
Labels: new pull request

#83 fix(SNP-400): Updates build badge route.
  README.md
Labels: bug, new pull request

#75 fix(): fix BottomSheet pop twice
  CHANGELOG.md
  lib/src/flexible_bottom_sheet.dart
  lib/src/flexible_bottom_sheet_route.dart
  test/bottom_sheet_test.dart
  test/not_expanded_bottom_sheet_test.dart
  test/sticky_bottom_sheet_test.dart
Labels: bug, new pull request

#76 fix(): snackbar issue fix
  CHANGELOG.md
  example/lib/standard_bottom_sheet_example.dart
  lib/src/flexible_bottom_sheet.dart
  lib/src/flexible_bottom_sheet_route.dart
  test/bottom_sheet_test.dart
  test/sticky_bottom_sheet_test.dart
Labels: new pull request, snackbar

#79 feat: update bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, new pull request

#88 SNP-304: bottom sheet offset
  CHANGELOG.md
  lib/src/flexible_bottom_sheet.dart
Labels: bug, new pull request

#85 SNP-529(#84) transparent space below content or no rounded corner on top
  CHANGELOG.md
  example/lib/main.dart
  example/lib/standard_bottom_sheet_example.dart
  lib/src/flexible_bottom_sheet.dart
  lib/src/flexible_bottom_sheet_route.dart
Labels: new pull request

#89 Dev 4.0.0: fix-bottom-sheet-pop-twice
  CHANGELOG.md
  lib/src/flexible_bottom_sheet.dart
  lib/src/flexible_bottom_sheet_route.dart
  test/bottom_sheet_test.dart
  test/not_expanded_bottom_sheet_test.dart
  test/sticky_bottom_sheet_test.dart
Labels: new pull request

#90 feat: Upgrade Flutter version
  .fvm/fvm_config.json
  CHANGELOG.md
  example/.fvm/fvm_config.json
  example/lib/bottom_sheet_based_on_content_height.dart
  example/lib/main.dart
  example/lib/standard_bottom_sheet_example.dart
  example/pubspec.yaml
  lib/bottom_sheet.dart
  lib/src/flexible_bottom_sheet.dart
  lib/src/flexible_bottom_sheet_route.dart
  lib/src/widgets/change_insets_detector.dart
  pubspec.yaml
  test/bottom_sheet_test.dart
  test/not_expanded_bottom_sheet_test.dart
  test/sticky_bottom_sheet_test.dart
Labels: new pull request

#91 Рackage version upgrade
  pubspec.yaml
Labels: new pull request

#93 Chore: fix github workflows for publish to pub
  .github/workflows/publish_to_pub.yml
Labels: new pull request
